- src/Checkbox/Checkbox.js
- src/Checkbox/index.js
> feat: add the Checkbox component

- src/TextField/TextField.js
- src/TextField/index.js
> feat: add the TextField component

- src/Select/Select.js
- src/Select/index.js
> feat: add the Select component

- src/Loader/Loader.js
- src/Loader/index.js
> feat: add the Loader component

- package-lock.json
- package.json
- src/Table/Table.js
- src/Table/index.js
- src/TableCell/TableCell.js
- src/TableCell/index.js
> feat: add the Table and TableCell components

- src/PageWrapper/PageWrapper.js
- src/PageWrapper/index.js
> feat: add the PageWrapper component

- package-lock.json
- package.json
- src/Link/Link.js
- src/Link/index.js
> feat: add the Link component

- .travis.yml
> ci: npm ci -> install

- src/ListItemDetail/__snapshots__/ListItemDetail.test.js.snap
- src/SubTitle/__snapshots__/SubTitle.test.js.snap
- src/WorkflowStatus/__snapshots__/WorkflowStatus.test.js.snap
- src/WorkflowStatusItem/__snapshots__/WorkflowStatusItem.test.js.snap
> test: fix snapshots

- src/PopupFormButton/PopupFormButton.js
> fix: update PopupFormButton Icon prop types

- package.json
> fix: specify all peer dependencies

- package.json
https://github.com/codfish/cod-ui/issues/36
Remove silent flag from test script.
> chore: remove silent flag from test script

- src/SubTitle/SubTitle.js
- src/SubTitle/__snapshots__/SubTitle.test.js.snap
- src/SubTitle/styles.js
> feat: update subtitle component to accept a class

- src/SubTitle/SubTitle.js
- src/SubTitle/styles.js
> Feat: add padded variant to subtitle component

- src/Checkbox/Checkbox.js
- src/PopupFormButton/PopupFormButton.js
- src/Select/Select.js
- src/TableCell/TableCell.js
- src/TextField/TextField.js
> fix: add missing prop types

- package.json
https://github.com/codfish/cod-ui/issues/40
Update devexpress after their MaterialUI update.
> chore: update devexpress dependencies

- package.json
> Revert "chore: update devexpress dependencies"

- src/Checkbox/Checkbox.js
- src/Select/Select.js
- src/TextField/TextField.js
> fix: update prop types

- package.json
https://github.com/codfish/cod-ui/issues/53
The dx-core dependency is needed and dx-grid-core should be added to remove a warning.
> feat: add devexpress dx-core and dx-grid-core deps

- src/Table/Table.js
closes #55
#55 
We need to add a filters prop to pass custom filters to the table.
> feat: add table column filters
